name: Release Please

on:
  push:
    branches: [main, alpha]

jobs:
  release:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v3.1.1
        id: app-token
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Create Release PR
        uses: googleapis/release-please-action@v5.0.0
        id: release
        with:
          config-file: .github/release-please-config.${{ github.ref_name }}.json
          manifest-file: .github/release-please-manifest.json
          target-branch: ${{ github.ref_name }}
          token: ${{ steps.app-token.outputs.token }}
      - name: Checkout Code
        if: steps.release.outputs.pr != '' && github.ref_name == 'alpha'
        uses: actions/checkout@v6.0.2
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Auto-merge Alpha Release PR
        if: steps.release.outputs.pr != '' && github.ref_name == 'alpha'
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh pr merge ${{ fromJson(steps.release.outputs.pr).number }} --rebase --auto
